url:
  quote_txn_req_url:
    https://63.push2.eastmoney.com/api/qt/clist/get?cb=jQuery112406326540387216384_1711515195823&pn=1&pz=6000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&wbp2u=|0|0|0|web&fid=f3&fs=m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23,m:0+t:81+s:2048&fields=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f12,f13,f14,f15,f16,f17,f18,f20,f21,f23,f24,f25,f22,f11,f62,f128,f136,f115,f152&_=1711515196014
  quote_10jqka_hotrank:
    https://dq.10jqka.com.cn/fuyao/hot_list_data/out/hot_list/v1/stock?stock_type=a&type=hour&list_type=normal
  quote_txn_req_history_url_sz:
    https://push2his.eastmoney.com/api/qt/stock/kline/get?fields1=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61&beg=20240409&end=20240411&ut=fa5fd1943c7b386f172d6893dbfba10b&rtntype=6&secid=0.stockcode&klt=101&fqt=1&cb=jsonp1711941323422
  quote_txn_req_history_url_sh:
    https://push2his.eastmoney.com/api/qt/stock/kline/get?fields1=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61&beg=20240409&end=20240411&ut=fa5fd1943c7b386f172d6893dbfba10b&rtntype=6&secid=1.stockcode&klt=101&fqt=1&cb=jsonp1711941323422
  quote_txn_req_history_url:
    https://push2his.eastmoney.com/api/qt/stock/kline/get?fields1=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13&fields2=f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61&beg=0&end=20240326&ut=fa5fd1943c7b386f172d6893dbfba10b&rtntype=6&secid=1.stockcode&klt=101&fqt=1&cb=jsonp1711941323422
  quote_10jqka_skyrocket:
    https://dq.10jqka.com.cn/fuyao/hot_list_data/out/hot_list/v1/stock?stock_type=a&type=hour&list_type=skyrocket
  quote_10jqka_industry:
    https://dq.10jqka.com.cn/fuyao/hot_list_data/out/hot_list/v1/plate?type=industry
  quote_10jqka_concept:
    https://dq.10jqka.com.cn/fuyao/hot_list_data/out/hot_list/v1/plate?type=concept
  quote_easymoney_index:
    https://24.push2.eastmoney.com/api/qt/clist/get?cb=jQuery11240018788837573413764_1712208347167&pn=1&pz=50&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&wbp2u=|0|0|0|web&fid=&fs=b:MK0010&fields=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f12,f13,f14,f15,f16,f17,f18,f20,f21,f23,f24,f25,f26,f22,f11,f62,f128,f136,f115,f152&_=1712208347320

  #板块和概念：
  #所属版块
  quote_easymoney_industry:
    https://datacenter.eastmoney.com/securities/api/data/get?type=RPT_F10_CORETHEME_BOARDTYPE&sty=SECUCODE%2CSECURITY_CODE%2CSECURITY_NAME_ABBR%2CBOARD_CODE%2CBOARD_NAME%2CIS_PRECISE%2CBOARD_RANK%2CBOARD_TYPE&filter=(SECUCODE%3D%22300407.SZ%22)&p=1&ps=&sr=1&st=BOARD_RANK&source=HSF10&client=PC&v=03525251440758925
  #概念详情：
  quote_easymoney_concept:
    https://datacenter.eastmoney.com/securities/api/data/v1/get?reportName=RPT_F10_CORETHEME_BOARDTYPE&columns=SECUCODE%2CSECURITY_CODE%2CSECURITY_NAME_ABBR%2CNEW_BOARD_CODE%2CBOARD_NAME%2CSELECTED_BOARD_REASON%2CIS_PRECISE%2CBOARD_RANK%2CBOARD_YIELD%2CDERIVE_BOARD_CODE&quoteColumns=f3~05~NEW_BOARD_CODE~BOARD_YIELD&filter=(SECUCODE%3D%22stock_code.SZ%22)(IS_PRECISE%3D%221%22)&pageNumber=1&pageSize=&sortTypes=1&sortColumns=BOARD_RANK&source=HSF10&client=PC&v=049141438068208876
  #题材详情
  quote_easymoney_theme:
    https://datacenter.eastmoney.com/securities/api/data/get?type=RPT_F10_CORETHEME_CONTENT&sty=SECUCODE%2CSECURITY_CODE%2CSECURITY_NAME_ABBR%2CKEYWORD%2CMAINPOINT%2CMAINPOINT_CONTENT%2CKEY_CLASSIF%2CKEY_CLASSIF_CODE%2CIS_POINT%2CIS_HISTORY&quoteColumns=&filter=(SECUCODE%3D%22300407.SZ%22)(KEY_CLASSIF_CODE%3C%3E%22001%22)&p=1&ps=&sr=1%2C1&st=KEY_CLASSIF_CODE%2CMAINPOINT&source=HSF10&client=PC&v=01718619355725599
  #所属行业：
  quote_easymoney_core_industry:
    https://datacenter.eastmoney.com/securities/api/data/v1/get?reportName=RPT_F10_CORETHEME_CONTENT&columns=SECUCODE%2CSECURITY_CODE%2CSECURITY_NAME_ABBR%2CKEYWORD%2CKEY_CLASSIF%2CKEY_CLASSIF_CODE%2CIS_POINT%2CIS_HISTORY&quoteColumns=&filter=(SECUCODE%3D%22300407.SZ%22)(IS_POINT%3D%221%22)(IS_HISTORY%3D%220%22)&pageNumber=1&pageSize=&sortTypes=1%2C1&sortColumns=KEY_CLASSIF_CODE%2CMAINPOINT&source=HSF10&client=PC&v=010002304026721287

  ###指数数据区域：
  #1 上证 000001
  index_shanghai_exchange_time_sharing:
    https://push2his.eastmoney.com/api/qt/stock/trends2/get?fields1=f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13&fields2=f51,f52,f53,f54,f55,f56,f57,f58&ut=fa5fd1943c7b386f172d6893dbfba10b&iscr=0&ndays=1&secid=1.000001&cb=jQuery35105528496742689353_1715096473681&_=1715096473691

  #2 资金走向
  index_money_flow_direction:
    https://push2his.eastmoney.com/api/qt/stock/fflow/daykline/get?cb=jQuery112308093756020195644_1715097385633&lmt=0&klt=101&fields1=f1%2Cf2%2Cf3%2Cf7&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61%2Cf62%2Cf63%2Cf64%2Cf65&ut=b2884a393a59ad64002292a3e90d46a5&secid=1.000001&_=1715097385634


  #3大单跟踪：该数据为html 其中page和ajax的为页码
  large_order_record:
    https://data.10jqka.com.cn/funds/ddzz/order/asc/page/1/ajax/1/free/1/

parm:
  quote_txn_req_max: 6000
  history_date : "2024-03-26"
  log_url : "log/stock_yyyy-mm-dd.log"

db:
  host: 112.74.98.79
  user: root
  password:  abcd1234#
  database: myquote
  port: 3306
